"""add contact_change_tokens table

Revision ID: 0ab0c112f7b2
Revises: 31be3555a315
Create Date: 2026-10-01 15:09:58.964150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab0c112f7b2'
down_revision: Union[str, None] = '31be3555a315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_change_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=10), nullable=False),
    sa.Column('new_value', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_change_tokens_code'), 'contact_change_tokens', ['code'], unique=False)
    op.create_index(op.f('ix_contact_change_tokens_id'), 'contact_change_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_contact_change_tokens_user_id'), 'contact_change_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_change_tokens_user_id'), table_name='contact_change_tokens')
    op.drop_index(op.f('ix_contact_change_tokens_id'), table_name='contact_change_tokens')
    op.drop_index(op.f('ix_contact_change_tokens_code'), table_name='contact_change_tokens')
    op.drop_table('contact_change_tokens')
    # ### end Alembic commands ###
