"""add unique constraint to purchase_history

Revision ID: 258cbe5ec4ec
Revises: e14e986dccd1
Create Date: 2026-09-17 14:53:28.754220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258cbe5ec4ec'
down_revision: Union[str, None] = 'e14e986dccd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_purchase_history_user_product', 'purchase_history', ['user_id', 'product_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_purchase_history_user_product', 'purchase_history', type_='unique')
    # ### end Alembic commands ###
