"""add list_members table for shared lists

Revision ID: 2f69e5b72932
Revises: 5bf503014be4
Create Date: 2026-05-19 14:51:22.906604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f69e5b72932'
down_revision: Union[str, None] = '5bf503014be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'user_id', name='_list_user_uc')
    )
    op.create_index(op.f('ix_list_members_id'), 'list_members', ['id'], unique=False)
    op.create_index(op.f('ix_list_members_list_id'), 'list_members', ['list_id'], unique=False)
    op.create_index(op.f('ix_list_members_user_id'), 'list_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_members_user_id'), table_name='list_members')
    op.drop_index(op.f('ix_list_members_list_id'), table_name='list_members')
    op.drop_index(op.f('ix_list_members_id'), table_name='list_members')
    op.drop_table('list_members')
    # ### end Alembic commands ###
