"""change password_reset_tokens: add code, attempts

Revision ID: 31be3555a315
Revises: 258cbe5ec4ec
Create Date: 2026-09-23 20:06:00.258574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31be3555a315'
down_revision: Union[str, None] = '258cbe5ec4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('code', sa.String(length=6), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('attempts', sa.Integer(), nullable=False))
    op.drop_index('ix_password_reset_tokens_token', table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_code'), 'password_reset_tokens', ['code'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_column('password_reset_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_code'), table_name='password_reset_tokens')
    op.create_index('ix_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=True)
    op.drop_column('password_reset_tokens', 'attempts')
    op.drop_column('password_reset_tokens', 'code')
    # ### end Alembic commands ###
