"""add indexes for search suggestions

Revision ID: 5bf503014be4
Revises: 17232de71aea
Create Date: 2026-05-19 13:32:03.232144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf503014be4'
down_revision: Union[str, None] = '17232de71aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_purchase_history_product_name'), 'purchase_history', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_history_product_name'), table_name='purchase_history')
    # ### end Alembic commands ###
