"""add indexes for foreign keys

Revision ID: 937fe4c20771
Revises: bf67362855ce
Create Date: 2026-04-21 18:12:29.251137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937fe4c20771'
down_revision: Union[str, None] = 'bf67362855ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_list_items_list_id'), 'list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_shopping_lists_owner_id'), 'shopping_lists', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_lists_owner_id'), table_name='shopping_lists')
    op.drop_index(op.f('ix_list_items_list_id'), table_name='list_items')
    # ### end Alembic commands ###
