"""add index for user_id in purchase_history

Revision ID: d13020ab02a4
Revises: 937fe4c20771
Create Date: 2026-04-21 18:14:40.279468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13020ab02a4'
down_revision: Union[str, None] = '937fe4c20771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_purchase_history_user_id'), 'purchase_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_history_user_id'), table_name='purchase_history')
    # ### end Alembic commands ###
