"""add index for name in list_items

Revision ID: dd9d21009354
Revises: d13020ab02a4
Create Date: 2026-04-21 18:34:24.137074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9d21009354'
down_revision: Union[str, None] = 'd13020ab02a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_list_items_name'), 'list_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_items_name'), table_name='list_items')
    # ### end Alembic commands ###
