"""remove description, position, is_archived

Revision ID: ea48645aa156
Revises: 2f69e5b72932
Create Date: 2026-09-09 11:26:51.502671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea48645aa156'
down_revision: Union[str, None] = '2f69e5b72932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list_items', 'position')
    op.drop_column('shopping_lists', 'description')
    op.drop_column('shopping_lists', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shopping_lists', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('list_items', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
